### ISSUE TITLE
[Bug] Comments lack HTML sanitization

### ISSUE THREAD

**Issue by tanky3024** [iv-org/invidious#4727]
![2024-06-03-074241_253x93_scrot](https://github.com/iv-org/invidious/assets/161307814/9bc7d532-8d48-44cb-90ef-35b29cce21d9)
![2024-06-03-074153_840x130_scrot](https://github.com/iv-org/invidious/assets/161307814/0f0bdca6-0518-41d2-92da-effd28c558fc)
See pic rel.

**Comment by SamantazFox** [comment]
Can you provide the invidious version?
This should already be fixed by #4576

**Comment by menestrel-mkmb** [comment]
Non-native english speaker.
I got that bug today, the instance version is `2024.07.28-3649d2e3 @ master`, I peeked on the issue above that a PR correction was mentioned, and even on the yewtu.be instance that was written that was working, now on `2024.08.01-d54c2df @ master` the bug persists.
