### ISSUE TITLE
Bots are attacking Invidious instances

### ISSUE THREAD

**Issue by unixfox** [iv-org/invidious#946]
I'm seeing bot behavior in the logs of my Invidious instance:
```
[03/Dec/2019:23:25:20 +0100] "GET /api/v1/videos/xxxxx HTTP/1.1" 200 67395 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/#{CHROME_VERSIONS[rand(CHROME_VERSIONS.size)]} Safari/537.36" - 587ms
[03/Dec/2019:23:25:21 +0100] "GET /api/v1/videos/xxxxx HTTP/1.1" 200 59593 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/#{CHROME_VERSIONS[rand(CHROME_VERSIONS.size)]} Safari/537.36" - 360ms
[03/Dec/2019:23:25:21 +0100] "GET /api/v1/videos/xxxxx HTTP/1.1" 200 77293 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/#{CHROME_VERSIONS[rand(CHROME_VERSIONS.size)]} Safari/537.36" - 1.031s
```

I'm pretty sure it's the root cause of public invidious instances being blocked by Google.

Does anyone know why they would want to abuse the invidious API? Is this related to [Freetube using Invidious API](https://github.com/omarroth/invidious/blob/master/CHANGELOG.md#version-0190-communities)?

I guess I'll have to deploy my antibot solution just like I did for my Searx instance...

**Comment by tleydxdy** [comment]
or it could be things like https://github.com/omarroth/invidious/issues/936

**Comment by unixfox** [comment]
Quick update:
So I had to block every API endpoint except from the one that the web interface of invidious use because the memory usage of invidious was growing too fast.
After blocking most of the API endpoint everything came to normal just like when I deployed my instance for the first time.

**Comment by tleydxdy** [comment]
I still get blocked even if I put auth on the website and only me can use the instance, so it's not just that.

**Comment by Pomilui** [comment]
> Does anyone know why they would want to abuse the invidious API? 

Hey, all.  I'm reporting a bug that I think it related to Google blocking the instance of this web stream:  invidio.us/watch?v=lIQ1X6MEqjM   

I remember a site called hooktube.com that attempted to get around using the Youtube API before Google lawyers, I imagine, instituted a Cease and Desist order on Hooktube.com.  

![image](https://user-images.githubusercontent.com/35349892/70167421-ae17fd00-1694-11ea-8a5c-120d48956bd4.png)

I'll follow this thread on what you all think, and I hope that the same doesn't happen to this project.  Thanks.

**Comment by elypter** [comment]
thats why we need many different anonymous contributors and anonymous instances in different countries.

**Comment by Vagmer** [comment]
> Is there any kind of Walkthrough available to get around Google blocking instances? Thanks.

Switch between instances often. Whenever the one you're using isn't working well enough, grab the same page you're currently on from a different instance. You can use the Invidition extension to make this much easier and more convenient.
That's it.

**Comment by Z3ROGRAV1TYx** [comment]
@elypter 
The thing that sucks comes with accounts, for people logged into one instance, they have to make an account on another and another and then import their lists etc. And stuff still doesn't sync between them. It can be a PITA, I think we should have some way to sync settings and subscriptions and history and everything.

The only one other thing being previous links to an instance shared to people will become useless if that instance goes down. That can be solved by sharing the youtube link i guess though

**Comment by Vagmer** [comment]
> The only one other thing being previous links to an instance shared to people will become useless if that instance goes down

Not that much. Links are interchangeable and in a quite easy to identify format. You can just change only the domain of a link (to `youtube.com` or `invidio.us` or another instance's domain) to make it valid again. Invidition again helps with this already as well (can automatically redirect any instance to a selected instance), though it would need to have a tweak to keep track of past instances that are no longer in the list to be futureproof in that manner.

**Comment by elypter** [comment]
for me it only redirects youtube links to an invidious instance. i would have suggested this as a feature but their bugtracker didnt let me register

**Comment by Perflyst** [comment]
Maybe they dont abuse your invidious instance, but just use it.
I have seen frontends which use the invidious API in the background, like https://popular100.biz/

**Comment by Booteille** [comment]
Open settings of the extension to do so.

The repo moved to codeberg.org if you need to open an issue. But the feature is already available as an opt-in setting.

**Comment by Z3ROGRAV1TYx** [comment]
> Not that much. Links are interchangeable and in a quite easy to identify format. You can just change only the domain of a link (to `youtube.com` or `invidio.us` or another instance's domain) to make it valid again.

Yes but not everyone who doesn't use Invidious knows that. Also everyone doesn't use Invidition.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
If you don't want to create an account or switching between instances makes yours unusable you can use an add-on called Fraidycat which allows you to follow content creators without having an account there. It lists them depending on who uploaded something for the last time and it's open source.
